services:
  xrouter-webhook-proxy:
    image: cr.yandex/${REGISTRY_ID}/${PROJECT_NAME}:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      tags:
        - cr.yandex/${REGISTRY_ID}/${PROJECT_NAME}:${VERSION}
        - cr.yandex/${REGISTRY_ID}/${PROJECT_NAME}:latest
